# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kodi TTS Addon
email: frank@feuerbacher.us
author:
  - name: "Frank Feuerbacher"
  - email: frank@feuerbacher.us
description: >- # this means to ignore newlines until "baseurl:"
  This site provides a private Kodi addon repository in order to simplify the installation
  and update of the Kodi TTS addon which is currently in Alpha. By installing this
  repository addon you will be able to easily install Kodi TTS and any dependencies.
baseurl: "/repo" # the subpath of your site, e.g. /blog
url: "https://feuerbacher.us" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: ""
github_username:  fbacher

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
minima:
  skin: dark
  hide_site_feed_link: true
  social_links: []
   # - title: Kodi TTS repository at GitHub
   #   icon: github
   #   url: "https://github.com/fbacher"
   # - title: Jekyll at X (formerly Twitter)
   #   icon: ""
   #   url: ""

remote_theme: "jekyll/minima@1e8a445"
header_pages: [ "INSTALL_LINUX" ]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - "*.mdp"
    - "**/*.mdp"
    - "gemfiles/"
    - "Gemfile"
    - "Gemfile.lock"
    - "node_modules/"
    - "vendor/bundle/"
    - "vendor/cache/"
    - "vendor/gems/"
    - "vendor/ruby/"
    - "index.markdown"
    - "about.markdown"
    - "*.awk"
    - "*_proto.xml"
    - ".git/*"
    - "**/*.sh"
    - "**/*.py"
    - "**/*.awk"
    - "**/*.proto"
    - "**/*_proto.xml"
    - "**/.git/*"
    - "**/index.markdown"
    - "**/about.markdown"
    - ".sass-cache/"
    - ".jekyll-cache/"
    - "**/resources/*"
